#!/bin/bash

set -e

Run() {
  export PKGCOPY="${TMPDIR}/${PKGNAME}"
  mkdir ${PKGCOPY}
  tar -x -C "${PKGCOPY}"
  $(dirname $(readlink -f $0))/../bin/test "${PKGCOPY}"
}

DoRun() {
  if ! Run >> ${LOGFILE} 2>&1; then
    notify-send -i error "${PKGNAME}: test failed" "Log file: file://${LOGFILE}\n\n${INFO}"
  else
    rm -rf ${TMPDIR}
  fi
}

Bootstrap() {
  if git branch | egrep "^\* \(no branch, rebasing "; then
    echo "$0: No test during rebase." >> /dev/stderr
    exit 0
  fi
  MYSELF=$(basename $0)
  export PKGDIR="$PWD"
  export PKGNAME=$(basename $PKGDIR)
  export LOG=($(git log HEAD^.. --oneline))
  export SHA=${LOG[0]}
  export INFO=$(git show --oneline --numstat)
  export TMPDIR=$(mktemp -d --tmpdir hookR.${SHA}.XXX)
  export LOGFILE=${TMPDIR}/${MYSELF}.log
  echo "${MYSELF}: Starting test, results are written to file://${LOGFILE}." >> /dev/stderr
  {
    echo "$0" "$@"
    echo "${LOG}"
    echo "${INFO}"
  } >> ${LOGFILE}

  git archive ${SHA} | DoRun &
}

Bootstrap
