#!/bin/bash

if [[ "$3" == 0 ]]; then
  echo "$(basename $0): File checkout, not installing"
  exit 0
fi

if [[ "$1" == "$2" ]]; then
  echo "$(basename $0): Ref not changed, not installing"
  exit 0
fi

. $(dirname $(readlink -f "$0"))/../bin/hook install
