#!/bin/bash
# Part of git-hookR, copyright 2013 Kirill Müller.
# License: GPL v3.  See http://www.gnu.org/copyleft/gpl.html for details.

if [[ "$1" == amend ]]; then
  echo "$(basename $0): Amended commit, will be tested by post-commit hook"
  exit 0
fi

. $(dirname $(readlink -f "$0"))/../bin/hook test
